name: Build and Test

# Trigger this workflow on push or pull request to main branch

on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  build:
    name: Build & Verify
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout the repo
      - name: Checkout repository
      - uses: actions/checkout@v3

      # Step 2: Set up Java
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 17

      # Step 3: Grant execute permissions to Gradle wrapper
      - name: Make gradlew executable
        run: chmod +x json-helper/gradlew

      # Step 4: Run build (clean, compile, test)
      - name: Run Gradle build
        working-directory: json-helper
        run: ./gradlew clean build
